# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26e44d8cf2128f25cd3bd1eafe7df5ff0eb302482de7c89351f4af6e2eca648b2aaa51448a56c8a0f48ac9da0c864f5df8ab92275b437468b5778d0e0718e1b5

test:
  secret_key_base: bc7e0bbeb4954a5c11cb70ee6bd6700ecdcfbfff907c781e348648a4dfd2a003fd876fa5df5e74c5d06c6dd3cb94774305f226d20f76dd723157630ea6d561bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
